// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Restaurant struct {
	ID                 uuid.UUID        `json:"id"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        pgtype.Text      `json:"description"`
	Status             string           `json:"status"`
	Category           pgtype.Text      `json:"category"`
	Rating             int32            `json:"rating"`
	TotalReviews       int32            `json:"total_reviews"`
	DeliveryFee        int64            `json:"delivery_fee"`
	MinOrderValue      int64            `json:"min_order_value"`
	PreparationTimeMin int32            `json:"preparation_time_min"`
	SupportsPickup     bool             `json:"supports_pickup"`
	SupportsDelivery   bool             `json:"supports_delivery"`
	LogoUrl            pgtype.Text      `json:"logo_url"`
	BannerUrl          pgtype.Text      `json:"banner_url"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type RestaurantAddress struct {
	ID           uuid.UUID        `json:"id"`
	RestaurantID uuid.UUID        `json:"restaurant_id"`
	Street       string           `json:"street"`
	Number       string           `json:"number"`
	Complement   pgtype.Text      `json:"complement"`
	City         string           `json:"city"`
	State        string           `json:"state"`
	ZipCode      string           `json:"zip_code"`
	Lat          float64          `json:"lat"`
	Lng          float64          `json:"lng"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type RestaurantOpeningHour struct {
	ID           uuid.UUID        `json:"id"`
	RestaurantID uuid.UUID        `json:"restaurant_id"`
	Weekday      int32            `json:"weekday"`
	OpensAt      int32            `json:"opens_at"`
	ClosesAt     int32            `json:"closes_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type RestaurantPaymentMethod struct {
	ID           uuid.UUID        `json:"id"`
	RestaurantID uuid.UUID        `json:"restaurant_id"`
	Method       string           `json:"method"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
